[package]
name = "github.com/jkfran/killport"
bin = "killport"
authors = ["Francisco Jimenez Cabrera <jkfran@gmail.com>"]
keywords = ["cli", "port", "process", "kill", "linux"]
description = """
A command-line tool to easily kill processes running on a specified port.
"""

[darwin]
x86_64 = { url = "{package.repository}/releases/download/v{version}/killport-x86_64-apple-darwin.tar.gz" }
aarch64 = { url = "{package.repository}/releases/download/v{version}/killport-aarch64-apple-darwin.tar.gz" }

[windows]
x86_64 = { url = "{package.repository}/releases/download/v{version}/killport-x86_64-windows-gnu.tar.gz" }

[linux]
x86_64 = { url = "{package.repository}/releases/download/v{version}/killport-x86_64-linux-gnu.tar.gz" }
aarch64 = { url = "{package.repository}/releases/download/v{version}/killport-aarch64-linux-gnu.tar.gz" }