[package]
name = "github.com/shadow1ng/fscan"
bin = "fscan"
authors = ["shadow1ng <shadow1ng@qq.com>"]
keywords = []
repository = "https://github.com/google/osv-scanner"
description = """
一款内网综合扫描工具，方便一键自动化、全方位漏扫扫描。
"""

[darwin]
x86_64 = { executable = "{package.repository}/releases/download/v{version}/darwin" }
aarch64 = { executable = "{package.repository}/releases/download/v{version}/darwin_arm64" }

[windows]
x86 = { executable = "{package.repository}/releases/download/v{version}/fscan32.exe" }
x86_64 = { executable = "{package.repository}/releases/download/v{version}/fscan64.exe" }

[linux]
x86 = { executable = "{package.repository}/releases/download/v{version}/fscan_386" }
x86_64 = { executable = "{package.repository}/releases/download/v{version}/fscan_amd64" }
armv7 = { executable = "{package.repository}/releases/download/v{version}/fscan_arm" }
aarch64 = { executable = "{package.repository}/releases/download/v{version}/fscan_arm64" }
