[package]
name = "github.com/sharkdp/fd"
bin = "fd"
repository = "https://github.com/sharkdp/fd"
description = """
A simple, fast and user-friendly alternative to 'find'
"""

[darwin]
x86_64 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-x86_64-apple-darwin.tar.gz", path = "/fd-v{version}-x86_64-apple-darwin" }
aarch64 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-x86_64-apple-darwin.tar.gz", path = "/fd-v{version}-x86_64-apple-darwin" }

[windows]
x86 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-i686-pc-windows-msvc.zip", path = "/fd-v{version}-i686-pc-windows-msvc" }
x86_64 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-x86_64-pc-windows-msvc.zip", path = "/fd-v{version}-x86_64-pc-windows-msvc" }

[linux]
x86 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-i686-unknown-linux-musl.tar.gz", path = "/fd-v{version}-i686-unknown-linux-musl" }
arm = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-arm-unknown-linux-musleabihf.tar.gz", path = "/fd-v{version}-arm-unknown-linux-musleabihf" }
armv7 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-arm-unknown-linux-musleabihf.tar.gz", path = "/fd-v{version}-arm-unknown-linux-musleabihf" }
x86_64 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-x86_64-unknown-linux-gnu.tar.gz", paht = "/fd-v{version}-x86_64-unknown-linux-gnu" }
aarch64 = { url = "{package.repository}/releases/download/v{version}/fd-v{version}-aarch64-unknown-linux-gnu.tar.gz", path = "/fd-v{version}-aarch64-unknown-linux-gnu" }
