[package]
name = "github.com/charmbracelet/vhs"
bin = "vhs"
authors = ["Charm <vt100@charm.sh>"]
keywords = []
repository = "https://github.com/charmbracelet/vhs"
description = """
Your CLI home video recorder 📼
"""

[darwin]
x86_64 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Darwin_x86_64.tar.gz" }
aarch64 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Darwin_arm64.tar.gz" }

[windows]
386 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Windows_i386.zip" }
x86_64 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Windows_x86_64.zip" }

[linux]
386 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Linux_i386.tar.gz" }
armv7 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Linux_armv7.tar.gz" }
x86_64 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Linux_x86_64.tar.gz" }
arm64 = { url = "{package.repository}/releases/download/v{version}/vhs_{version}_Linux_arm64.tar.gz" }
