[package]
name = "github.com/sharkdp/bat"
bin = "bat"
repository = "https://github.com/sharkdp/bat"
description = """
A cat(1) clone with wings.
"""

[darwin]
x86_64 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-x86_64-apple-darwin.tar.gz", path = "/bat-v{version}-x86_64-apple-darwin" }
aarch64 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-x86_64-apple-darwin.tar.gz", path = "/bat-v{version}-x86_64-apple-darwin" }

[windows]
x86 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-i686-pc-windows-msvc.zip", path = "/bat-v{version}-i686-pc-windows-msvc" }
x86_64 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-x86_64-pc-windows-msvc.zip", path = "/bat-v{version}-x86_64-pc-windows-msvc" }

[linux]
x86 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-i686-unknown-linux-musl.tar.gz", path = "/bat-v{version}-i686-unknown-linux-musl" }
arm = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-arm-unknown-linux-musleabihf.tar.gz", path = "/bat-v{version}-arm-unknown-linux-musleabihf" }
armv7 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-arm-unknown-linux-musleabihf.tar.gz", path = "/bat-v{version}-arm-unknown-linux-musleabihf" }
x86_64 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-x86_64-unknown-linux-gnu.tar.gz", paht = "/bat-v{version}-x86_64-unknown-linux-gnu" }
aarch64 = { url = "{package.repository}/releases/download/v{version}/bat-v{version}-aarch64-unknown-linux-gnu.tar.gz", path = "/bat-v{version}-aarch64-unknown-linux-gnu" }
